alias Open_FB_links='ipython3 /home/amir/github/working/Facebook_posts_links/Open_FB_links.py'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to\ full|percentage"'
alias c='rm c_program; gcc -o c_program c_program.c ; ./c_program'
alias c_p='cd ~/github/C-programming-A_Modern_Approach-book-Exercises-/ ; subl c_program.c ; (gopen *.pdf &); gnome-terminal ; (jl *.ipynb &) ; sleep 3; exit'
alias c_server='read -p '\''Enter last 3 digits from server IP address: '\'' ip;  sudo ssh lfd-server@192.168.8.'
alias c_subl='subl && sleep 3 && wmctrl -r :ACTIVE: -e 0,0,0,1960,660'
alias calc='gcalccmd'
alias copyfrom='xclip -sel cli <'
alias copyto='xsel -b >'
alias d='du -sh -B M * | sort -nr'
alias egrep='egrep --color=auto'
alias facebook-links='ipython3 /home/amir/github/working/Facebook_posts_links/facebook-links.py'
alias fgrep='fgrep --color=auto'
alias freemem='cat /proc/meminfo | grep -i '\''inactive:\|memfree:'\'''
alias g='read a; firefox google.com/search?q="$a"; sleep 2; exit'
alias grep='grep --color=auto'
alias h1-zong='nmcli d w c H1-Zong password wifi@lfd'
alias i='ipython3'
alias jazz='nmcli d w c Jazz-LTE-438A password 34969900'
alias jl='jupyter-lab'
alias jp='jupyter-notebook'
alias l='ls -CF'
alias la='ls -A'
alias lfd_jazz='nmcli d w c lfd_jazz password lfd@12345'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias p='python3 -c '\''t=input(); print(eval(t))'\'''
alias ping='ping 8.8.8.8'
alias rm='mv -t ~/.local/share/Trash/files'
alias sharjeel='bash ~/awesome-sharjeel-wifi-connect.wifi'
alias si='xclip -selection clipboard -t image/png -o >'
alias t='trans :ar'
alias telenor='nmcli d w c Telenor\ 4G-D9BF password 91423958'
alias wl='nmcli d w r; sleep 10; nmcli d w l'
alias zong2='nmcli d w c ZONG\ MBB-E5573-2592 password 78624687'
alias zongd='nmcli d w c ZONG\ MBB-E5573-D164 password 34886114'
