#!/bin/bash
rm ~/ab.txt
a=`ls | cut -d "_" -f1 | wc -l`
for i in `ls | cut -d "_" -f1 | head -$(( $a -1))` ; do
	cd $i*
	for f in *.*; do printf "%s\n" "${f##*.}" | sort -u ; done | sort -u  >> ~/ab.txt
	cd ../
done
cat ~/ab.txt | sort -u