#!/bin/bash

sudo systemctl stop naclient
sudo systemctl start naclient

# m=`sudo systemctl status naclient | grep Active\:\ | cut -d: -f2 | cut -d " " -f2`
# if [[ $m == "active" ]] ; then 
# 	:
# else
# 	echo "Starting naclient"
# 	sudo systemctl start naclient
# fi

/opt/sslvpn-plus/naclient/gui/naclient.sh 2>/dev/null
sleep 4
# ssh server_admin@192.168.62.12
#echo -n "ENTER your P@ssw0rd: "
#ssh root@192.168.62.12
ssh  192.168.62.12

