#!/usr/bin/python3
import requests
import os
from bs4 import BeautifulSoup
import sys
# url = input("paste your URL: ")
try:
	url = sys.argv[1]
except:
	url = input("Paste you URL please: ")
soup = BeautifulSoup(requests.get(url).text, "lxml")
for i in soup.select("a"):
    try:
        l = i['href']
        if l.startswith("/url?q="):
            m = l.strip("/url?q=")
            os.system("firefox " + m)
    except:
        pass
